wandb_version: 1

batch_size:
  value: 32
conv_filters:
  value:
  - 32
  - 64
  - 128
dropout_rate:
  value: 0.36667585789345175
epochs:
  value: 20
fc_layer_size:
  value: 128
learning_rate:
  value: 0.00017465523707034454
optimizer:
  value: rmsprop
