wandb_version: 1

batch_size:
  value: 32
conv_filters:
  value:
  - 32
  - 64
  - 128
dropout_rate:
  value: 0.6289926784036886
epochs:
  value: 20
fc_layer_size:
  value: 128
learning_rate:
  value: 0.0005022812750659347
optimizer:
  value: adam
