wandb_version: 1

batch_size:
  value: 32
conv_filters:
  value:
  - 16
  - 32
  - 64
dropout_rate:
  value: 0.4497049825762481
epochs:
  value: 20
fc_layer_size:
  value: 128
learning_rate:
  value: 0.0001325859916310972
optimizer:
  value: rmsprop
