wandb_version: 1

batch_size:
  value: 64
conv_filters:
  value:
  - 32
  - 64
  - 128
dropout_rate:
  value: 0.6003982682681674
epochs:
  value: 20
fc_layer_size:
  value: 64
learning_rate:
  value: 0.003872553976204911
optimizer:
  value: adam
