wandb_version: 1

batch_size:
  value: 16
conv_filters:
  value:
  - 8
  - 16
  - 32
  - 64
dropout_rate:
  value: 0.46402172340174097
epochs:
  value: 20
fc_layer_size:
  value: 128
learning_rate:
  value: 0.0002947559511082836
optimizer:
  value: adam
