wandb_version: 1

batch_size:
  value: 16
conv_filters:
  value:
  - 24
  - 24
  - 24
  - 24
dropout_rate:
  value: 0.3528493053828972
epochs:
  value: 20
fc_layer_size:
  value: 128
learning_rate:
  value: 0.001397906449649352
optimizer:
  value: adam
