wandb_version: 1

batch_size:
  value: 64
conv_filters:
  value:
  - 64
  - 32
  - 16
  - 8
dropout_rate:
  value: 0.6477339585004396
epochs:
  value: 20
fc_layer_size:
  value: 64
learning_rate:
  value: 0.004872065915047665
optimizer:
  value: rmsprop
