wandb_version: 1

batch_size:
  value: 64
conv_filters:
  value:
  - 24
  - 24
  - 24
  - 24
dropout_rate:
  value: 0.6629150840068323
epochs:
  value: 20
fc_layer_size:
  value: 512
learning_rate:
  value: 0.00010665916695677245
optimizer:
  value: adam
