wandb_version: 1

batch_size:
  value: 32
conv_filters:
  value:
  - 8
  - 16
  - 32
  - 64
dropout_rate:
  value: 0.3989152505965143
epochs:
  value: 20
fc_layer_size:
  value: 256
learning_rate:
  value: 0.000648108648768623
optimizer:
  value: rmsprop
