_wandb:
    value:
        cli_version: 0.22.0
        e:
            17bfs7mvxbnyobgd4pk13etantw96bw5:
                codePath: Model_IA.ipynb
                codePathLocal: Model_IA.ipynb
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "1001563090944"
                        used: "183644684288"
                email: morlioncolin@gmail.com
                executable: c:\Python313\python.exe
                git:
                    commit: 063a9a34421c1af5d0f000f5da90aba7de1e0121
                    remote: https://github.com/xMokiii/Workshop2025.git
                gpu: NVIDIA GeForce RTX 4090 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 9728
                      memoryTotal: "17171480576"
                      name: NVIDIA GeForce RTX 4090 Laptop GPU
                      uuid: GPU-5b01b30e-7636-33af-082e-a6f178abd6c0
                host: ToasterEdition
                memory:
                    total: "33986576384"
                os: Windows-11-10.0.26100-SP0
                program: c:\Users\morli\Perso\Workshop2025\Model_IA.ipynb
                python: CPython 3.13.5
                root: c:\Users\morli\Perso\Workshop2025
                startedAt: "2025-09-25T13:14:42.725739Z"
                writerId: 17bfs7mvxbnyobgd4pk13etantw96bw5
        m:
            - "1": epoch/epoch
              "6":
                - 3
              "7": []
            - "2": epoch/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.13.5
        t:
            "1":
                - 2
                - 3
            "2":
                - 2
                - 3
            "3":
                - 2
                - 7
                - 16
                - 38
                - 39
            "4": 3.13.5
            "5": 0.22.0
            "8":
                - 1
                - 3
            "10":
                - 20
            "12": 0.22.0
            "13": windows-amd64
architecture:
    value: CNN
batch_size:
    value: 32
epochs:
    value: 30
img_height:
    value: 180
img_width:
    value: 180
learning_rate:
    value: 0.001
optimizer:
    value: Adam
