_wandb:
    value:
        cli_version: 0.22.0
        e:
            o7ma1j3e9gnrezpa2e3hb2tlvzpmw0lm:
                codePath: Model_IA.ipynb
                codePathLocal: Model_IA.ipynb
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1000186310656"
                        used: "195528601600"
                email: morlioncolin@gmail.com
                executable: c:\Users\Morlion\anaconda3\envs\mycnn-env\python.exe
                git:
                    commit: f1f506f82da7bf2ecbaf2ec4bdb640e5bfba569b
                    remote: https://github.com/xMokiii/Workshop2025.git
                gpu: NVIDIA GeForce RTX 2060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1920
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 2060
                      uuid: GPU-c438d479-7db7-9d15-99a7-4fb0a237dfee
                host: Benoit
                memory:
                    total: "17126817792"
                os: Windows-10-10.0.26100-SP0
                program: d:\Users\Morlion\Workshop2025\Model_IA.ipynb
                python: CPython 3.10.18
                root: d:\Users\Morlion\Workshop2025
                startedAt: "2025-09-26T00:04:07.103807Z"
                writerId: o7ma1j3e9gnrezpa2e3hb2tlvzpmw0lm
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 2
                - 3
            "2":
                - 2
                - 3
            "3":
                - 2
                - 14
            "4": 3.10.18
            "5": 0.22.0
            "8":
                - 1
                - 3
            "12": 0.22.0
            "13": windows-amd64
batch_size:
    value: 32
conv_filters:
    value:
        - 8
        - 16
        - 32
        - 64
dropout_rate:
    value: 0.3989152505965143
epochs:
    value: 20
fc_layer_size:
    value: 256
learning_rate:
    value: 0.000648108648768623
optimizer:
    value: rmsprop
